const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
test('OT: permisos, conflictos, sesiones, cierre separado, stock histórico y restauración de persistencia',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mesa-workflow-'));
 process.env.DB_PATH=path.join(dir,'test.db');
 process.env.MESA_DEMO='1';
 const {server,db}=require('../server');
 const token=crypto.randomBytes(32).toString('hex'),operator=crypto.randomBytes(32).toString('hex'),technician=crypto.randomBytes(32).toString('hex');
 const session=(value,id)=>db.prepare("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,datetime('now','+1 hour'))").run(crypto.createHash('sha256').update(value).digest('hex'),id);
 session(token,1);session(operator,4);session(technician,2);
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const base='http://127.0.0.1:'+server.address().port;
 const send=async(url,method='GET',body,as=token)=>{const res=await fetch(base+url,{method,headers:{'Content-Type':'application/json',Cookie:'mesa_session='+as},body:body?JSON.stringify(body):undefined});return {status:res.status,data:await res.json()};};
 const ok=async(...args)=>{const r=await send(...args);assert.ok(r.status<300,JSON.stringify(r));return r.data;};
 let orderId;
 try{
  assert.equal((await send('/api/users','GET',undefined,operator)).status,403);
  db.prepare('DELETE FROM user_action_permissions WHERE user_id=?').run(4);
  db.prepare('INSERT INTO user_action_permissions (user_id,action,allowed) VALUES (?,?,1)').run(4,'orders.read');
  assert.equal((await send('/api/orders','POST',{requester_id:4,priority:'Alta',classification:'Mantenimiento Correctivo',reported_failure:'No autorizado'},operator)).status,403);
  db.prepare('INSERT INTO user_action_permissions (user_id,action,allowed) VALUES (?,?,1)').run(4,'orders.create');
  db.prepare('INSERT INTO user_action_permissions (user_id,action,allowed) VALUES (?,?,1)').run(2,'assets.read');
  db.prepare('INSERT INTO user_area_permissions (user_id,area,allowed) VALUES (?,?,1)').run(2,'Área inexistente');
  assert.deepEqual(await ok('/api/assets','GET',undefined,technician),[]);
  const asset=await ok('/api/assets','POST',{code:'FIX-001',name:'Fixture de prueba',category:'Maquinaria',asset_type:'Fixture',area:'Área de prueba',original_code:'LEG-77',alias_codes:'LEG-77, FIX-OLD',operational_status:'Operación restringida',operational_status_cause:'Pendiente de revisión',administrative_status:'Activo'});
  const assetDetail=await ok('/api/assets/'+asset.id);
  assert.equal(assetDetail.asset_type,'Fixture');
  assert.equal(assetDetail.original_code,'LEG-77');
  assert.equal(assetDetail.operational_status,'Operación restringida');
  assert.equal(assetDetail.operational_status_cause,'Pendiente de revisión');
  const plan=await ok('/api/preventives','POST',{asset_id:asset.id,title:'Inspección de fixture',frequency:'1 mes',next_date:'2026-10-01',responsible_id:2,template_code:'PM-FIX-01',applies_when:'Antes de arranque',instructions:'Revisar fijaciones y prueba funcional'});
  const meter=await ok('/api/assets/'+asset.id+'/meter-readings','POST',{reading:125.5,note:'Lectura de turno'});
  assert.equal(meter.reading,125.5);
  assert.equal((await ok('/api/assets/'+asset.id+'/meter-readings')).current_reading,125.5);
  assert.equal((await send('/api/assets/'+asset.id+'/meter-readings','POST',{reading:120},technician)).status,403);
  assert.equal((await send('/api/assets/'+asset.id+'/meter-readings','POST',{reading:100})).status,400);
  assert.equal((await send('/api/assets/'+asset.id,'PATCH',{operating_hours:200})).status,400);
  const plans=await ok('/api/preventives'); const createdPlan=plans.find(item=>item.id===plan.id); assert.equal(createdPlan.version,1);
  await ok('/api/preventives/'+plan.id,'PATCH',{version:1,instructions:'Revisar fijaciones, guardas y prueba funcional'});
  assert.equal((await ok('/api/preventives')).find(item=>item.id===plan.id).version,2);
  assert.equal((await send('/api/preventives/'+plan.id,'PATCH',{version:1,title:'Edición obsoleta'})).status,409);
  const generated=await ok('/api/preventives/'+plan.id+'/order','POST');
  assert.match((await ok('/api/orders/'+generated.id)).reported_failure,/guardas/);
  assert.equal((await ok('/api/preventives/'+plan.id+'/order','POST')).already_exists,true);
  const revisions=await ok('/api/preventives/'+plan.id+'/revisions');
  assert.deepEqual(revisions.map(r=>r.version),[2,1]);
  assert.equal(revisions[1].snapshot.instructions,'Revisar fijaciones y prueba funcional');
  assert.equal(revisions[0].user_id,1);
  const assignedRevision=(await ok('/api/orders/'+generated.id)).preventive_revision;
  assert.equal(assignedRevision.version,2);
  assert.match(assignedRevision.snapshot.instructions,/guardas/);
  assert.throws(()=>db.prepare('UPDATE preventive_plan_revisions SET reason=? WHERE plan_id=?').run('Sobrescrito',plan.id),/inmutable/);
  assert.throws(()=>db.prepare('DELETE FROM preventive_plan_revisions WHERE plan_id=?').run(plan.id),/inmutable/);
  assert.equal((await send('/api/preventives/'+plan.id+'/revisions','GET',undefined,operator)).status,403);
  db.prepare('INSERT INTO user_action_permissions (user_id,action,allowed) VALUES (?,?,1)').run(2,'preventives.read');
  assert.equal((await send('/api/preventives/'+plan.id+'/revisions','GET',undefined,technician)).status,403);
  assert.equal((await send('/api/preventives/'+plan.id,'PATCH',{version:2,title:'Cambiar histórico'})).status,409);
  const draft=await ok('/api/preventives','POST',{asset_id:asset.id,title:'Plan de prueba atómica',frequency:'1 mes',next_date:'2026-10-02'});
  db.exec("CREATE TEMP TRIGGER fail_revision BEFORE INSERT ON preventive_plan_revisions WHEN NEW.version=2 BEGIN SELECT RAISE(ABORT,'Fallo simulado'); END");
  assert.ok((await send('/api/preventives/'+draft.id,'PATCH',{version:1,title:'No debe persistir'})).status>=400);
  db.exec('DROP TRIGGER fail_revision');
  assert.equal((await ok('/api/preventives')).find(p=>p.id===draft.id).title,'Plan de prueba atómica');
  assert.equal((await ok('/api/preventives/'+draft.id+'/revisions')).length,1);
  const historyCount=db.prepare('SELECT COUNT(*) n FROM preventive_plan_revisions').get().n;
  require('../lib/preventive-history').migrate(db);
  assert.equal(db.prepare('SELECT COUNT(*) n FROM preventive_plan_revisions').get().n,historyCount);
  const taskUrl='/api/preventives/'+draft.id+'/tasks';
  const calendarUrl='/api/preventives/'+draft.id+'/calendar?from=2026-02-01&to=2026-07-31';
  assert.equal((await ok(calendarUrl)).configuration_pending,true);
  const taskPayload={title:'Revisión mensual',interval_unit:'months',interval_value:1,anchor_date:'2026-01-31',version:1};
  assert.equal((await send(taskUrl,'POST',taskPayload,technician)).status,403);
  const monthlyTask=await ok(taskUrl,'POST',taskPayload);
  assert.equal((await send(taskUrl,'POST',taskPayload)).status,409);
  const quarterlyTask=await ok(taskUrl,'POST',{...taskPayload,title:'Revisión trimestral',interval_value:3,version:2});
  const projection=await ok(calendarUrl);
  assert.equal(projection.configuration_pending,false);
  assert.deepEqual(projection.occurrences.filter(o=>o.task_id===quarterlyTask.id).map(o=>o.base_date),['2026-04-30','2026-07-31']);
  assert.equal(projection.occurrences.filter(o=>o.task_id===monthlyTask.id).length,6);
  assert.deepEqual(await ok(calendarUrl),projection);
  assert.equal((await send(calendarUrl,'GET',undefined,technician)).status,403);
  assert.equal((await ok('/api/preventives/'+draft.id+'/revisions'))[0].snapshot.tasks.length,2);
  const taskOrder=await ok('/api/preventives/'+draft.id+'/order','POST');
  assert.equal((await ok('/api/orders/'+taskOrder.id)).preventive_revision.snapshot.tasks.length,2);
  assert.equal((await send(taskUrl,'POST',{...taskPayload,version:3})).status,409);
  const recurring=await ok('/api/preventives','POST',{asset_id:asset.id,title:'Plan recurrente',frequency:'Explícita por tarea',next_date:'2026-01-31'});
  const template=await ok('/api/preventive-templates','POST',{code:'TPL-FIX',family:'Fixture',title:'Rutina fixture',instructions:'Aplicar estándar',tasks:[{title:'Revisar guardas',interval_unit:'months',interval_value:1,anchor_date:'2026-01-31'}]});
  const templated=await ok('/api/preventives','POST',{asset_id:asset.id,title:'Plan desde plantilla',frequency:'Pendiente',next_date:'2026-01-31'});
  const applied=await ok('/api/preventives/'+templated.id+'/apply-template','POST',{template_id:template.id,version:1});assert.equal(applied.tasks,1);assert.equal((await ok('/api/preventives/'+templated.id+'/tasks')).length,1);
  const rt=await ok('/api/preventives/'+recurring.id+'/tasks','POST',taskPayload);
  const occurrenceUrl='/api/preventives/'+recurring.id+'/occurrences';
  const occurrenceInput={task_id:rt.id,occurrence_index:1,version:2};
  assert.equal((await send(occurrenceUrl,'POST',occurrenceInput,technician)).status,403);
  assert.equal((await send(occurrenceUrl,'POST',{...occurrenceInput,version:1})).status,409);
  const concurrentOccurrences=await Promise.all([ok(occurrenceUrl,'POST',occurrenceInput),ok(occurrenceUrl,'POST',occurrenceInput)]);
  assert.equal(concurrentOccurrences[0].work_order_id,concurrentOccurrences[1].work_order_id);
  assert.equal(concurrentOccurrences.filter(o=>o.replayed).length,1);
  assert.equal(concurrentOccurrences[0].base_date,'2026-02-28');
  const nextOccurrence=await ok(occurrenceUrl,'POST',{...occurrenceInput,occurrence_index:2});
  assert.equal(nextOccurrence.base_date,'2026-03-31');
  assert.notEqual(nextOccurrence.work_order_id,concurrentOccurrences[0].work_order_id);
  assert.equal((await ok('/api/orders/'+nextOccurrence.work_order_id)).scheduled_at,'2026-03-31');
  assert.equal((await send('/api/preventives/'+recurring.id+'/order','POST')).status,409);
  assert.equal((await send('/api/preventives/'+draft.id+'/occurrences','POST',{task_id:monthlyTask.id,occurrence_index:1,version:3})).status,409);
  const sequenceBefore=db.prepare('SELECT * FROM folio_sequences').all();
  const orderCount=db.prepare('SELECT COUNT(*) n FROM work_orders').get().n;
  db.exec("CREATE TEMP TRIGGER fail_occurrence BEFORE INSERT ON preventive_occurrences BEGIN SELECT RAISE(ABORT,'Fallo simulado de ocurrencia'); END");
  assert.ok((await send(occurrenceUrl,'POST',{...occurrenceInput,occurrence_index:3})).status>=400);
  db.exec('DROP TRIGGER fail_occurrence');
  assert.equal(db.prepare('SELECT COUNT(*) n FROM work_orders').get().n,orderCount);
  assert.deepEqual(db.prepare('SELECT * FROM folio_sequences').all(),sequenceBefore);
  require('../lib/preventive-occurrences').migrate(db);
  assert.equal((await ok(occurrenceUrl)).length,2);
  assert.throws(()=>db.prepare('DELETE FROM preventive_occurrences WHERE plan_id=?').run(recurring.id),/conservarse/);
  assert.throws(()=>db.prepare('UPDATE preventive_occurrences SET base_date=? WHERE plan_id=?').run('2027-01-01',recurring.id),/inmutables/);
  assert.equal((await ok(occurrenceUrl,'POST',occurrenceInput)).work_order_id,concurrentOccurrences[0].work_order_id);
  const compliance=await ok('/api/preventives/'+recurring.id+'/compliance?from=2026-02-01&to=2026-04-30&as_of=2026-04-30');
  assert.deepEqual(compliance.occurrences.map(row=>row.status),['V','V']);
  assert.equal(compliance.compliance_percent,0);
  assert.equal((await send('/api/preventives/'+recurring.id+'/compliance?from=2026-04-30&to=2026-02-01','GET',undefined,operator)).status,403);
  assert.equal((await send('/api/preventives/'+recurring.id+'/compliance?from=2026-04-30&to=2026-02-01')).status,400);
  const grouped=await ok('/api/preventives','POST',{asset_id:asset.id,title:'Plan agrupable',frequency:'Explícita por tarea',next_date:'2026-05-31'});
  const groupedA=await ok('/api/preventives/'+grouped.id+'/tasks','POST',{...taskPayload,title:'Inspección eléctrica',anchor_date:'2026-05-31',version:1});
  const groupedB=await ok('/api/preventives/'+grouped.id+'/tasks','POST',{...taskPayload,title:'Inspección mecánica',anchor_date:'2026-05-31',version:2});
  const groupedOrder=await ok('/api/preventives/'+grouped.id+'/occurrences/group','POST',{version:3,occurrences:[{task_id:groupedA.id,occurrence_index:0},{task_id:groupedB.id,occurrence_index:0}]});
  assert.equal((await ok('/api/preventives/'+grouped.id+'/occurrences')).filter(row=>row.work_order_id===groupedOrder.work_order_id).length,2);
  assert.equal((await ok('/api/orders/'+groupedOrder.work_order_id)).preventive_execution.items.length,2);
  const checklistItem=await ok('/api/preventives/'+grouped.id+'/tasks/'+groupedA.id+'/checklist','POST',{position:1,prompt:'¿Equipo sin fugas?',required:true});
  const groupedOccurrence=(await ok('/api/preventives/'+grouped.id+'/occurrences')).find(row=>row.task_id===groupedA.id);
  assert.equal((await send('/api/preventives/'+grouped.id+'/tasks/'+groupedA.id+'/checklist','POST',{position:1,prompt:'Duplicado'})).status,409);
  assert.equal((await send('/api/preventives/'+grouped.id+'/occurrences/'+groupedOccurrence.id+'/checklist','POST',{answers:[] })).status,400);
  const answers=await ok('/api/preventives/'+grouped.id+'/occurrences/'+groupedOccurrence.id+'/checklist','POST',{answers:[{item_id:checklistItem.id,answer:'Sí',notes:'Correcto'}]});
  assert.equal(answers.complete,true);
  assert.equal((await ok('/api/preventives/'+grouped.id+'/occurrences/'+groupedOccurrence.id+'/checklist')).items[0].answer,'Sí');
  const groupedOrderDetail=await ok('/api/orders/'+groupedOrder.work_order_id);
  const rescheduled=await ok('/api/preventives/'+grouped.id+'/occurrences/'+groupedOccurrence.id+'/reschedule','POST',{scheduled_at:'2026-06-02',reason:'Ajuste de ventana operativa',version:groupedOrderDetail.version});
  assert.equal(rescheduled.base_date,'2026-05-31');
  assert.equal((await ok('/api/preventives/'+grouped.id+'/upcoming?from=2026-05-01&to=2026-06-30')).occurrences.length,4);
  assert.equal((await send('/api/preventives/'+grouped.id+'/occurrences/'+groupedOccurrence.id+'/reschedule','POST',{scheduled_at:'2026-06-03',reason:'Sin versión'})).status,409);
  const executionUrl='/api/orders/'+nextOccurrence.work_order_id;
  let executionOrder=await ok(executionUrl);
  await ok(executionUrl,'PATCH',{version:executionOrder.version,technician_id:1,actions:'Revisión de la tarea completada'});
  const transitionExecution=async(to,extra={})=>ok(executionUrl+'/transitions','POST',{version:(await ok(executionUrl)).version,to,...extra});
  await transitionExecution('En proceso');
  await transitionExecution('Pendiente de validación',{closure_notes:'Primera ejecución documentada'});
  executionOrder=await ok(executionUrl);
  assert.equal(executionOrder.closure_notes,'Primera ejecución documentada');
  assert.equal(executionOrder.preventive_execution.state,'Pendiente de validación');
  assert.equal(executionOrder.preventive_execution.validated_at,null);
  const executionBase=executionOrder.preventive_execution.base_date;
  await transitionExecution('En proceso',{reason:'Completar verificación'});
  assert.equal((await ok(executionUrl)).preventive_execution.executed_at,null);
  await transitionExecution('Pendiente de validación',{closure_notes:'Segunda ejecución documentada'});
  executionOrder=await ok(executionUrl);
  assert.equal((await send(executionUrl+'/validate','POST',{version:executionOrder.version},operator)).status,403);
  db.exec("CREATE TEMP TRIGGER fail_execution BEFORE INSERT ON preventive_execution_events WHEN NEW.event='validated' BEGIN SELECT RAISE(ABORT,'Fallo simulado de ejecución'); END");
  assert.ok((await send(executionUrl+'/validate','POST',{version:executionOrder.version})).status>=400);
  db.exec('DROP TRIGGER fail_execution');
  assert.equal((await ok(executionUrl)).version,executionOrder.version);
  await ok(executionUrl+'/validate','POST',{version:executionOrder.version,comment:'Validación funcional'});
  executionOrder=await ok(executionUrl);
  assert.equal(executionOrder.preventive_execution.state,'Validada');
  assert.ok(executionOrder.preventive_execution.validated_at);
  await transitionExecution('Abierta',{reason:'Revisión posterior'});
  executionOrder=await ok(executionUrl);
  assert.equal(executionOrder.preventive_execution.state,'Reabierta');
  assert.equal(executionOrder.preventive_execution.validated_at,null);
  assert.equal(executionOrder.preventive_execution.base_date,executionBase);
  assert.deepEqual(executionOrder.preventive_execution.events.map(e=>e.event),['terminated','returned','terminated','validated','reopened']);
  assert.equal(executionOrder.preventive_execution.events[0].notes,'Primera ejecución documentada');
  await transitionExecution('Cancelada',{reason:'Se cancela la intervención reabierta'});
  assert.equal((await ok(executionUrl)).preventive_execution.state,'Cancelada');
  assert.equal((await ok(occurrenceUrl)).find(o=>o.work_order_id===concurrentOccurrences[0].work_order_id).execution.state,'Sin ejecución registrada');
  assert.throws(()=>db.exec('DELETE FROM preventive_execution_events'),/inmutable/);
  for(const [url,method,b] of [['/api/orders/1','PATCH',{actions:'No autorizado'}],['/api/orders/1/validate','POST',{}],['/api/inventory/1/movement','POST',{type:'Ajuste',quantity:50}]]){
   assert.equal((await send(url,method,b,operator)).status,403);
  }
  const visible=await ok('/api/orders','GET',undefined,operator);
  visible.forEach(o=>assert.equal(Object.hasOwn(o,'material_cost'),false));
  assert.deepEqual((await ok('/api/catalogs','GET',undefined,operator)).inventory,[]);
  const payload={requester_id:1,technician_id:1,asset_id:1,priority:'Alta',classification:'Mantenimiento Correctivo',reported_failure:'Prueba sintética'};
  const autonomous=await ok('/api/orders','POST',{requester_id:1,priority:'Media',classification:'Mantenimiento Autónomo',asset_id:1,reported_failure:'Rutina autónoma',autonomous_checklist:'Limpiar y revisar guardas'});
  assert.equal((await ok('/api/orders/'+autonomous.id)).autonomous_checklist,'Limpiar y revisar guardas');
  const [a,b]=await Promise.all([ok('/api/orders','POST',{...payload,idempotency_key:'ot-a'}),ok('/api/orders','POST',{...payload,idempotency_key:'ot-b'})]);
  assert.notEqual(a.folio,b.folio);orderId=a.id;
  const locationOrder=await ok('/api/orders','POST',{requester_id:1,priority:'Media',classification:'Mantenimiento Correctivo',location:'Línea de ensamble',reported_failure:'Atención en ubicación sin activo'});
  assert.equal((await ok('/api/orders/'+locationOrder.id)).location,'Línea de ensamble');
  assert.ok((await ok('/api/orders?area=Corte')).every(order=>order.asset_area==='Corte'));
  const agenda=await ok('/api/agenda');
  assert.ok(agenda.orders.some(order=>order.id===a.id));
  assert.ok(agenda.technicians.some(technician=>technician.id===2));
  const downtime=await ok('/api/downtime-events','POST',{asset_id:1,cause:'Paro sintético',started_at:'2026-09-08T10:00:00Z',work_order_ids:[a.id,b.id],request_key:'downtime-a'});
  assert.equal((await ok('/api/downtime-events')).find(event=>event.id===downtime.id).order_count,2);
  assert.equal((await send('/api/downtime-events/'+downtime.id,'PATCH',{finished_at:'2026-09-08T11:00:00Z'},operator)).status,403);
  await ok('/api/downtime-events/'+downtime.id,'PATCH',{finished_at:'2026-09-08T11:00:00Z',reason:'Se confirmó la causa y se liberó el equipo'});
  assert.equal((await ok('/api/orders','POST',{...payload,idempotency_key:'ot-a'})).id,a.id);
  const url='/api/orders/'+a.id;
  let order=await ok(url);
  assert.equal((await send(url,'PATCH',{actions:'Sin versión'})).status,409);
  await ok(url,'PATCH',{actions:'Reparación y prueba funcional',version:order.version});
  assert.equal((await send(url,'PATCH',{actions:'Edición antigua',version:order.version})).status,409);
  assert.equal((await send(url,'PATCH',{materials:[],version:order.version})).status,400);
  const itemId=(await ok('/api/inventory','POST',{code:'TEST-10',name:'Material sintético',category:'Refacción',unit:'pieza',stock:10,min_stock:0,max_stock:20,unit_cost:20})).id;
  const getItem=async()=>(await ok('/api/inventory')).find(i=>i.id===itemId);
  const issue={type:'Salida',quantity:3,work_order_id:a.id,version:(await getItem()).version,request_key:'issue-a'};
  const issued=await ok('/api/inventory/'+itemId+'/movement','POST',issue);
  const origin=db.prepare('SELECT * FROM inventory_movements WHERE id=?').get(issued.id);
  assert.equal((await getItem()).stock,7);
  assert.equal((await ok('/api/inventory/'+itemId+'/movement','POST',issue)).replayed,true);
  const returned={type:'Devolución',quantity:1,return_of:issued.id,version:(await getItem()).version,request_key:'return-a'};
  await ok('/api/inventory/'+itemId+'/movement','POST',returned);
  await ok('/api/inventory/'+itemId+'/movement','POST',returned);
  assert.equal((await getItem()).stock,8);
  assert.equal((await ok(url)).material_cost,40);
  await ok('/api/inventory/'+itemId,'PATCH',{unit_cost:99});
  assert.deepEqual(db.prepare('SELECT * FROM inventory_movements WHERE id=?').get(issued.id),origin);
  const version=(await getItem()).version;
  const concurrent=await Promise.all(['race-a','race-b'].map(request_key=>send('/api/inventory/'+itemId+'/movement','POST',{type:'Salida',quantity:7,version,request_key})));
  assert.equal(concurrent.filter(r=>r.status===201).length,1);
  assert.equal(concurrent.filter(r=>r.status===409).length,1);
  assert.equal((await getItem()).stock,1);
  const over=await send('/api/inventory/'+itemId+'/movement','POST',{type:'Salida',quantity:2,version:(await getItem()).version,request_key:'over'});
  assert.equal(over.status,400);assert.equal((await getItem()).stock,1);
  await ok(url+'/time-entries','POST',{user_id:1,started_at:'2026-09-07T07:00:00Z',finished_at:'2026-09-07T09:00:00Z'});
  await ok(url+'/time-entries','POST',{user_id:2,started_at:'2026-09-07T07:00:00Z',finished_at:'2026-09-07T09:00:00Z'});
  assert.equal((await ok(url)).labor_hours,4);
  assert.equal((await send(url+'/time-entries','POST',{user_id:1,started_at:'2026-09-07T08:00:00Z',finished_at:'2026-09-07T10:00:00Z'})).status,409);
  order=await ok(url);await ok(url+'/transitions','POST',{to:'En proceso',version:order.version});
  order=await ok(url);await ok(url+'/transitions','POST',{to:'Pausada',version:order.version});
  assert.equal(db.prepare('SELECT COUNT(*) n FROM work_order_time_entries WHERE work_order_id=? AND finished_at IS NULL').get(a.id).n,0);
  order=await ok(url);await ok(url+'/transitions','POST',{to:'En proceso',version:order.version});
  order=await ok(url);await ok(url+'/transitions','POST',{to:'Pendiente de validación',version:order.version,closure_notes:'Trabajo y pruebas funcionales documentadas'});
  order=await ok(url);assert.equal(order.status,'Pendiente de validación');assert.equal(order.closed_at,null);
  await ok(url+'/validate','POST',{version:order.version});
  order=await ok(url);assert.equal(order.status,'Completada');assert.equal(order.validation_status,'Validada');
  const historical=order.validated_at;
  assert.equal((await send(url+'/transitions','POST',{to:'Abierta',version:order.version})).status,400);
  await ok(url+'/transitions','POST',{to:'Abierta',version:order.version,reason:'Revisión posterior de prueba'});
  assert.equal((await ok(url)).validated_at,historical);
  assert.equal((await ok(url)).material_cost,40);
  assert.deepEqual(db.prepare('SELECT * FROM inventory_movements WHERE id=?').get(issued.id),origin);
  assert.equal(db.prepare('PRAGMA foreign_key_check').all().length,0);
 }finally{await new Promise(r=>server.close(r));db.close();}
 const {DatabaseSync}=require('node:sqlite');const reopened=new DatabaseSync(process.env.DB_PATH);
 assert.equal(reopened.prepare('SELECT status FROM work_orders WHERE id=?').get(orderId).status,'Abierta');
 reopened.close();fs.rmSync(dir,{recursive:true,force:true});
});
