# Generated by Django 5.2.6 on 2026-09-28 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_importrow_cell_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('document_number', models.CharField(max_length=120)),
                ('source_order_version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('sha256', models.CharField(max_length=64)),
                ('pdf_content', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_work_order_documents', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='maintenance.workorder')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('work_order', 'version'), name='unique_work_order_document_version')],
            },
        ),
    ]
